### ISSUE TITLE
Can't set style of cell with empty cell text

### ISSUE THREAD

**Issue by neoCobol** [RomanPavelko/SwiftExcel#10]
Hello,

I'm having an issue with the style of celle when I'm writing them.
Cells that are empty or have whitespaces doesn't apply style (borders....).
Is there a solution to it ?

Thank you ,
Have a nice day

**Comment by RomanPavelko** [comment]
Hi @neoCobol,

Fixed. Please update to the latest version 1.0.15 and thank you for this observation.
Roman.

**Comment by neoCobol** [comment]
Hello  @RomanPavelko

Thank you for your time and reactivity !

I confirm that the problem is now gone.

Have a nice day and you must know that I really appreciate your work :)
