### ISSUE TITLE
Dates cannot be written

### ISSUE THREAD

**Issue by metkhoo** [RomanPavelko/SwiftExcel#15]
Hi Roman,

If I write to a cell with

write.Write("2020-01-15", 1, 1, DataType.Text);

The cell gets the text value correctly but it stays as "text".
If  I open Excel and edit the cell and just press enter then it converts it to DateTime as I expect (i.e. it is the correct date/time format for my regiion)

My question: 
How do I write to the cell so that it accepts it as a Date/Time without having to edit each cell in Excel?

Thanks (and geat work here!)

/Marcus

**Comment by metkhoo** [comment]
Oh, and same question for TRUE/FALSE cells

**Comment by RomanPavelko** [comment]
Hi Marcus,

Thanks for reaching out. For setting cell format you need to use styles and unfortunately this is not part of the standard SwiftExcel package. You are free to use trial/evaluation version for how long you want and try it out yourself. The package itself is available [here](https://www.nuget.org/packages/SwiftExcel.Pro).

A sample code to output a date with the format you need:
```
var style = new Style
{
    NumberFormat = NumberFormat.Custom("yyyy-mm-dd")
};

var dateToExport = new DateTime(2020, 1, 15);
using (var ew = new ExcelWriter("C:\\temp\\test.xlsx", style))
{
    ew.Write($"{dateToExport.ToOADate()}", 1, 2, 1, 1, DataType.Number);
}
```

Other examples can be found [here](https://swiftexcel.pro/).

**Comment by metkhoo** [comment]
Thanks for the swift response.  I can get dates as decimals via the OLEAutomation date as you suggested.  I am writing a tool that I wish to distribute.  What is the licencing model in this case? Also there will be a finite number of customers.  Thanks

**Comment by RomanPavelko** [comment]
@metkhoo let's take it offline. On the website there is a _Support_ link at the bottom of the screen. Email me there.
