### ISSUE TITLE
cannot install via nuget in .net framework 4.8.1

### ISSUE THREAD

**Issue by gdsoftdev** [RomanPavelko/SwiftExcel#16]
Hi,

I have a project using .net framework 4.8.1 and when I install the package via nuget I get the following error message:
Impossible d’installer le package « SwiftExcel.Pro 1.1.3 ». Vous essayez d’installer ce package dans un projet ciblant « .NETFramework,Version=v4.8.1 », mais le package ne contient aucun fichier de contenu ou référence d’assembly compatible avec cette infrastructure. Pour plus d’informations, contactez le créateur du package.

Can you help me please ?
Thanks

Jérémy

**Comment by RomanPavelko** [comment]
Hi @gdsoftdev, thanks for reaching out.

The package was successfully tested out on 4.8.1, here is a screenshot of successful installation, build and run:
![image](https://github.com/RomanPavelko/SwiftExcel/assets/58891901/767d6ebf-1155-4c79-a180-f9189c2f13c7)

Try installing it on an empty console project targeting 4.8.1 to narrowing down the issue. If it installs then there must be something wrong with your original project you were trying to install it to.

**Comment by gdsoftdev** [comment]
Thanks for your answer, I'll give it a try for a next project
