### ISSUE TITLE
Exception during file writing

### ISSUE THREAD

**Issue by JuniorRaja** [RomanPavelko/SwiftExcel#18]
Hi,

I'm trying to write a xlsx file from a dataset. I get the following exception when I'm running in production. 
Then same code works in my environment.

System.Memory; The type initializer for 'PerTypeValues`1' threw an exception. 

![code](https://github.com/RomanPavelko/SwiftExcel/assets/102710826/11422d34-b420-4c1a-b149-ef092b8284fa)

**Comment by RomanPavelkoMGM** [comment]
Hi @JuniorRaja. 

Your code looks good. Could you please share what line of your code throws this exception and a full stacktrace of it? This is highly likely not related to the library but to the project / environment itself. It's hard to say more without additional details.

**Comment by RomanPavelko** [comment]
Hi @JuniorRaja,

Your code looks good. Could you please share what line of your code throws this exception and a full stacktrace of it? This is highly likely not related to the library but to the project / environment itself. It's hard to say more without additional details.

**Comment by JuniorRaja** [comment]
Hi @RomanPavelko 

Trying to write the xlsx file through an Windows Service installed in the server. As mentioned earlier, the package works in dev environment.

The stack trace is as below,
`Stack Trace

4/1/2024 5:40:10 PM: System.Memory; The type initializer for 'PerTypeValues`1' threw an exception.
4/1/2024 5:40:10 PM:    at EODService.DailyReports.writeXLSXSwift(DataTable dsOutput, String ReportName, String Report_Fk)
   at EODService.DailyReports.generateReports()
   at EODService.EODService.EODExecution()
   at EODService.EODService.timer1_Tick(Object sender, ElapsedEventArgs e)
   at System.Timers.Timer.MyTimerCallback(Object state)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback(Int32 id)
`

**Comment by JuniorRaja** [comment]
Hi @RomanPavelko 

Thanks to you. I was able to resolve the earlier said exception by splitting the data and writing in chunks. Now, I'm able to work with string and number columns. I'm unable write "date" in the excel. It is being written as string only.

How can I write the dates as Date Format
Thanks in advance.

**Comment by RomanPavelko** [comment]
Congratulations on resolving the previous issue.

Unfortunately SwiftExcel doesn't support exporting dates. You will need to look into the prepaid [.Pro version ](https://swiftexcel.pro/). Feel free to use the [trial version](https://www.nuget.org/packages/SwiftExcel.Pro) for however you need.

Here is a code example how to output a date type with .Pro version:
```
var style = new Style
{ 
    NumberFormat = NumberFormat.Custom("dd/mmm/yyyy") 
};
  
 
var dateToExport = new DateTime(2022, 11, 13); 
using (var ew = new ExcelWriter("C:\\temp\\test.xlsx", style)) 
{ 
    ew.Write($"{dateToExport.ToOADate()}", 1, 2, 1, 1, DataType.Number); 
}
```
