### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by jmilamtx** [RomanPavelko/SwiftExcel#19]
Hi, I am really wanting to try your library. It seems really good. I keep getting this error when running this code:

	Dim ew As SwiftExcel.Pro.ExcelWriter = New SwiftExcel.Pro.ExcelWriter("C:\\users\\public\\test.xlsx")

I get this error. I tried looking for the version of .unsafe below but it won't install.

FileLoadException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by RomanPavelko** [comment]
I tried to reproduce it with VB console project using Core 3.1, .NET 6.0 and 7.0. Everything works as expected. Would you mind sharing your solution project so I can take a look?

**Comment by RomanPavelko** [comment]
No worries, glad you were able to figure it out.
