### ISSUE TITLE
Adding Formula From The Code is Not Allowed

### ISSUE THREAD

**Issue by sar0z** [RomanPavelko/SwiftExcel#3]
It would be a great function to enable adding formulas from inside. I have created if for myself. I would love to see in the upcoming feature.

**Comment by RomanPavelko** [comment]
> It would be a great function to enable adding formulas from inside. I have created if for myself. I would love to see in the upcoming feature.

I agree, it would be nice to have. I'll think how it can be added without harming the performance.

**Comment by RomanPavelko** [comment]
> It would be a great function to enable adding formulas from inside. I have created if for myself. I would love to see in the upcoming feature.

Formulas were added in recent release 1.0.8
