### ISSUE TITLE
Strong Name needed

### ISSUE THREAD

**Issue by dingdonglars** [RomanPavelko/SwiftExcel#4]
I am porting from .NET Framework to netstandard and need a replacement for the xPortTools .NET xPorter (http://www.xporttools.net/). I came across your SwiftExcel which seems to exactly what I need. Great! It is really nice that you stream the output, as my app sometimes need to write quite large files.

However, I need it to have a strong name. Would you accept a PR that just adds signing with a new (not password protected) key?

**Comment by RomanPavelko** [comment]
> I am porting from .NET Framework to netstandard and need a replacement for the xPortTools .NET xPorter (http://www.xporttools.net/). I came across your SwiftExcel which seems to exactly what I need. Great! It is really nice that you stream the output, as my app sometimes need to write quite large files.
> 
> However, I need it to have a strong name. Would you accept a PR that just adds signing with a new (not password protected) key?

PR was merged, thanks for the contribution, @dingdonglars
