### ISSUE TITLE
Error while opening excel file after applying date format.

### ISSUE THREAD

**Issue by PLebakula** [RomanPavelko/SwiftExcel#7]
Hello ,

I created a style for formatting the date values as below. It throws error while opening the excel file. 

**Style:**
![image](https://user-images.githubusercontent.com/110677141/183088536-b6445962-d268-4780-bed0-0577e82ae870.png)

**Write to excel:**
![image](https://user-images.githubusercontent.com/110677141/183088432-8a2768d3-db9f-4425-aeb4-987884853f41.png)

**Error while opening the excel:**
![image](https://user-images.githubusercontent.com/110677141/183089123-262ec7b6-b610-40c7-99b2-f34fd327a339.png)

Is there any thing i am missing. please let me know. 
Thanks in advance.

**Comment by RomanPavelko** [comment]
When outputting a date as an actual Excel's cell **date** format you need to use a formula, this is from my original email:

`ew.Write("DATE(2022, 7, 28)", 1, 5, 1, 3, DataType.CustomFormula);`
