### ISSUE TITLE
DataTable to Excel - Performance 

### ISSUE THREAD

**Issue by PLebakula** [RomanPavelko/SwiftExcel#8]
Hi Team,

I have a requirement to write DataTable to excel. I looping the write method for achieving this because, write() allows only one cell value at a time. I am not able to see great performance in my case . 

I am trying to write 200 000 records and 65 columns. it takes 4 mins approximately.  Is there any effective method to increase the performance ? we are planning to purchase the license as soon as we are satisfied with the outcome.

![image](https://user-images.githubusercontent.com/110677141/183817470-21b8c86d-d4cd-4333-88df-02d2f675e70d.png)

Thank you!

**Comment by RomanPavelko** [comment]
Hi PLebakula,

Thank you for providing your code sample. The usage of the library on your screenshot looks good and it should give you the best performance it can produce. I tried to output the same amount of cells and I get an execution time around 25 seconds which is expected for such amount of data. 

Having said that I'd like to confirm with you if there is another bottleneck here. Could you please simplify your example removing any interaction with `dtLineItems` ? Just hardcode max row count with 200 000 and max col count with 65 and output some random string as a value. Let's see how much time it will take to execute and output this data when you don't access `dtLineItems` variable at all.

**Comment by PLebakula** [comment]
> Hi PLebakula,
> 
> Thank you for providing your code sample. The usage of the library on your screenshot looks good and it should give you the best performance it can produce. I tried to output the same amount of cells and I get an execution time around 25 seconds which is expected for such amount of data.
> 
> Having said that I'd like to confirm with you if there is another bottleneck here. Could you please simplify your example removing any interaction with `dtLineItems` ? Just hardcode max row count with 200 000 and max col count with 65 and output some random string as a value. Let's see how much time it will take to execute and output this data when you don't access `dtLineItems` variable at all.

**Comment by PLebakula** [comment]
Hi RomanPavelko,

We have tried to avoid the references of dtLineItems and execute it with random string. It takes 35 seconds for 2000 000 records and 65 columns. 
After that , I kept row count, column count in one variable instead of using dtLineItems. There was some 5-10 seconds of improvement, It still takes 3min for 200 000 records. But in case of reading the value from dtLineItems I cant avoid using dr.ItemArray(). 

In this case, Is there anything we can do to decrease the "time to export" to ~1 min.

Thank you !

**Comment by RomanPavelko** [comment]
I see, I'm glad you could verify that library still works with expected performance on your end when you "feed" string values into it. So apparently the performance bottleneck here is the `DataTable` and how you access values from it. By any chance, are you making a round trip to the database each time you process a new row? If yes that could be 200 000 DB calls which you must avoid at all cost. I would recommend to divide this process into 2 parts:
1. Fetch all data from your `DataTable/DB` into a `List<List<string>>` collection.
2. Use this in-memory collection to loop through it and output it into Excel using the library.

**Comment by PLebakula** [comment]
Hi RomanPavelko,

We have obtained the license of swift excel. We have got the key as shown below.

LicenseInfo.SerialNumber = "asaAsdfADGwqw==123" (Example only).

Can you please provide some guidelines how to use this in our solution.

Thank you!

Regards,
Purushotham
